/*
 * Adds `fontScale` to MainActivity's `android:configChanges`, so changing the
 * system font size does not tear down and recreate the Activity.
 *
 * This is a debugging aid, not a recommendation. By default Android treats a
 * font-size change as an ordinary configuration change and recreates the
 * Activity, which rebuilds the whole native view tree — so any measurement bug
 * in `PlainText` is hidden behind a fresh start. Declaring `fontScale` takes
 * that away: React Native instead calls `requestLayout()` on every attached
 * surface (`ReactHostImpl.onConfigurationChanged`, gated on the
 * `enableFontScaleChangesUpdatingLayout` feature flag, which defaults to on),
 * which exercises re-measurement of a live tree. That is the path where a
 * cached sp-to-px factor in a shadow node shows up as stale text size.
 *
 * Note that `DeviceInfoModule` only compares `fontScale` in `onHostResume`, so
 * with this declared the JS-side `Dimensions` / `PixelRatio.getFontScale()`
 * stay stale until the app is backgrounded and resumed. Native layout updates,
 * JS does not. That asymmetry is itself worth seeing.
 *
 * Why a plugin: `android/` is gitignored and regenerated by prebuild, so a
 * hand-edit to AndroidManifest.xml does not survive.
 */

const { AndroidConfig, withAndroidManifest } = require('expo/config-plugins');

// Android 12+ "Bold text" is a separate config change; left out because a font
// weight change does not affect PlainText's measurement the way scale does.
const CONFIG_CHANGE = 'fontScale';

const withFontScaleConfigChanges = (config) =>
  withAndroidManifest(config, (cfg) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(cfg.modResults);

    const current = activity.$['android:configChanges'] ?? '';
    const values = current.split('|').filter(Boolean);

    // Idempotent: prebuild may run against an already-patched manifest.
    if (!values.includes(CONFIG_CHANGE)) {
      values.push(CONFIG_CHANGE);
      activity.$['android:configChanges'] = values.join('|');
    }

    return cfg;
  });

module.exports = withFontScaleConfigChanges;
